
#include "relay.h"
#include "func.h"




key_function_st key_func[NBR_KEY_PADS][NBR_KEYS_PER_PAD] =
{
  {
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
  },
  {
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY, VA_RELAY_ET},
    {FUNC_RELAY_GROUP, VA_RELAY_GROUP_TUPA},
    {FUNC_RELAY_GROUP,VA_RELAY_GROUP_KHH},
  }

};